"""add_platform_models_accounts_clusters_issues_plans_risks_engagement_nps_lifecycle

Revision ID: 205c68fd3cc3
Revises: bfa89a3f629d
Create Date: 2026-05-13 09:24:07.409463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205c68fd3cc3'
down_revision: Union[str, Sequence[str], None] = 'bfa89a3f629d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tam_user_id', sa.Integer(), nullable=True),
    sa.Column('tam_type', sa.String(length=50), nullable=True),
    sa.Column('service_days_json', sa.Text(), nullable=True),
    sa.Column('purchased_products_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tam_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_number'), ['account_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)

    op.create_table('account_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_cluster_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('console_url', sa.String(length=500), nullable=True),
    sa.Column('openshift_version', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_phase', sa.String(length=100), nullable=True),
    sa.Column('master_nodes', sa.Integer(), nullable=True),
    sa.Column('compute_nodes', sa.Integer(), nullable=True),
    sa.Column('vcpu_total', sa.Integer(), nullable=True),
    sa.Column('memory_gb', sa.Float(), nullable=True),
    sa.Column('cloud_provider', sa.String(length=50), nullable=True),
    sa.Column('arch', sa.String(length=50), nullable=True),
    sa.Column('health_state', sa.String(length=50), nullable=True),
    sa.Column('critical_alerts', sa.Integer(), nullable=True),
    sa.Column('upgrade_available', sa.String(length=50), nullable=True),
    sa.Column('upgrade_state', sa.String(length=50), nullable=True),
    sa.Column('last_telemetry_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_clusters_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_clusters_id'), ['id'], unique=False)

    op.create_table('account_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sso_username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('is_tam_contact', sa.Boolean(), nullable=False),
    sa.Column('is_org_admin', sa.Boolean(), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('relationship_status', sa.String(length=50), nullable=True),
    sa.Column('team', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_contacts_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_contacts_id'), ['id'], unique=False)

    op.create_table('account_entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('entitlement_name', sa.String(length=500), nullable=False),
    sa.Column('service_level', sa.String(length=100), nullable=True),
    sa.Column('support_level', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_entitlements_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_entitlements_id'), ['id'], unique=False)

    op.create_table('account_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('affects_versions', sa.Text(), nullable=True),
    sa.Column('target_version', sa.String(length=100), nullable=True),
    sa.Column('fix_versions', sa.Text(), nullable=True),
    sa.Column('linked_cases', sa.Text(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_issues_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_issues_id'), ['id'], unique=False)

    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initiative_type', sa.String(length=100), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('customer_owner', sa.String(length=255), nullable=True),
    sa.Column('tam_name', sa.String(length=255), nullable=True),
    sa.Column('dee_name', sa.String(length=255), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('start_quarter', sa.String(length=10), nullable=True),
    sa.Column('close_year', sa.Integer(), nullable=True),
    sa.Column('close_quarter', sa.String(length=10), nullable=True),
    sa.Column('details_html', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plans_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_id'), ['id'], unique=False)

    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('customer_area', sa.String(length=100), nullable=False),
    sa.Column('adoption_difficulty', sa.String(length=50), nullable=True),
    sa.Column('customer_knowledge', sa.String(length=50), nullable=True),
    sa.Column('team_turnover', sa.String(length=50), nullable=True),
    sa.Column('py_engagement', sa.String(length=50), nullable=True),
    sa.Column('q1_engagement', sa.String(length=50), nullable=True),
    sa.Column('q2_engagement', sa.String(length=50), nullable=True),
    sa.Column('q3_engagement', sa.String(length=50), nullable=True),
    sa.Column('q4_engagement', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagements_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagements_id'), ['id'], unique=False)

    op.create_table('nps_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tam_user_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tam_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nps_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nps_surveys_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nps_surveys_id'), ['id'], unique=False)

    op.create_table('product_lifecycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('phases_json', sa.Text(), nullable=True),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('ga_date', sa.Date(), nullable=True),
    sa.Column('full_support_end', sa.Date(), nullable=True),
    sa.Column('maintenance_end', sa.Date(), nullable=True),
    sa.Column('eus_end', sa.Date(), nullable=True),
    sa.Column('customer_environment', sa.String(length=50), nullable=True),
    sa.Column('qty_installs', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_lifecycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_lifecycles_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_lifecycles_id'), ['id'], unique=False)

    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('probability', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('customer_area', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_id'), ['id'], unique=False)

    op.create_table('touchpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('customer_area', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touchpoints_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_touchpoints_id'), ['id'], unique=False)

    op.create_table('assessment_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('respondent_name', sa.String(length=255), nullable=False),
    sa.Column('responses_json', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_responses_id'), ['id'], unique=False)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sso_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='tam'))
        batch_op.add_column(sa.Column('tam_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('certifications_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_days_config_json', sa.Text(), nullable=True))

    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_guides_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_constraint('fk_guides_account_id', type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('service_days_config_json')
        batch_op.drop_column('skills_tags')
        batch_op.drop_column('certifications_json')
        batch_op.drop_column('tam_type')
        batch_op.drop_column('role')
        batch_op.drop_column('sso_username')
        batch_op.drop_column('full_name')
        batch_op.drop_column('email')

    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_responses_id'))

    op.drop_table('assessment_responses')
    with op.batch_alter_table('touchpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touchpoints_id'))
        batch_op.drop_index(batch_op.f('ix_touchpoints_account_id'))

    op.drop_table('touchpoints')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_id'))
        batch_op.drop_index(batch_op.f('ix_risks_account_id'))

    op.drop_table('risks')
    with op.batch_alter_table('product_lifecycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_lifecycles_id'))
        batch_op.drop_index(batch_op.f('ix_product_lifecycles_account_id'))

    op.drop_table('product_lifecycles')
    with op.batch_alter_table('nps_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nps_surveys_id'))
        batch_op.drop_index(batch_op.f('ix_nps_surveys_account_id'))

    op.drop_table('nps_surveys')
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagements_id'))
        batch_op.drop_index(batch_op.f('ix_engagements_account_id'))

    op.drop_table('engagements')
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plans_id'))
        batch_op.drop_index(batch_op.f('ix_action_plans_account_id'))

    op.drop_table('action_plans')
    with op.batch_alter_table('account_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_issues_id'))
        batch_op.drop_index(batch_op.f('ix_account_issues_account_id'))

    op.drop_table('account_issues')
    with op.batch_alter_table('account_entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_entitlements_id'))
        batch_op.drop_index(batch_op.f('ix_account_entitlements_account_id'))

    op.drop_table('account_entitlements')
    with op.batch_alter_table('account_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_account_contacts_account_id'))

    op.drop_table('account_contacts')
    with op.batch_alter_table('account_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_clusters_id'))
        batch_op.drop_index(batch_op.f('ix_account_clusters_account_id'))

    op.drop_table('account_clusters')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_number'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
