"""add admin_users table and guide access_token

Revision ID: bfa89a3f629d
Revises: 1410bb110e0b
Create Date: 2026-04-10 09:59:44.066706

"""
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa89a3f629d'
down_revision: Union[str, Sequence[str], None] = '1410bb110e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_id'), ['id'], unique=False)

    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=64), nullable=False, server_default='temp'))
        batch_op.create_index(batch_op.f('ix_guides_access_token'), ['access_token'], unique=False)

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id FROM guides")).fetchall()
    for row in rows:
        conn.execute(
            sa.text("UPDATE guides SET access_token = :token WHERE id = :id"),
            {"token": secrets.token_urlsafe(24), "id": row[0]},
        )

    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.alter_column('access_token', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guides_access_token'))
        batch_op.drop_column('access_token')

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_id'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
